alias Jaang.SearchManager

SearchManager.create_search_term(%{term: "kimchi", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "tofu", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "rice", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "ramen", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "mushroom", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "beef", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "rice cake", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "dumpling", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "seaweed", counter: 1, store_id: 1})
SearchManager.create_search_term(%{term: "noodles", counter: 1, store_id: 1})

SearchManager.create_search_term(%{term: "kimchi", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "tofu", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "rice", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "ramen", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "mushroom", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "beef", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "rice cake", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "dumpling", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "seaweed", counter: 1, store_id: 2})
SearchManager.create_search_term(%{term: "noodles", counter: 1, store_id: 2})

SearchManager.create_search_term(%{term: "kimchi", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "tofu", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "rice", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "ramen", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "mushroom", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "beef", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "rice cake", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "dumpling", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "seaweed", counter: 1, store_id: 3})
SearchManager.create_search_term(%{term: "noodles", counter: 1, store_id: 3})
